import type { AgentManifestResult } from "../agentManifest.js";
import type { RenderedFile } from "./claude.js";

export function renderCursor(manifest: AgentManifestResult): RenderedFile[] {
  const globs = manifest.domainsTouched.map((d) => `  - ${d}/**`).join("\n");

  const activeRules = manifest.rules
    .map((r) => {
      const hintPart = r.hint ? ` — _${r.hint}_` : "";
      return `- \`${r.path}\` — ${r.reason}${hintPart}`;
    })
    .join("\n");

  const content = `---
description: ContextForge active task — auto-derived from forge manifest
globs:
${globs || "  []"}
alwaysApply: false
---

# Active task

${manifest.task}

## Instruction

${manifest.instruction}

## Domains touched

${manifest.domainsTouched.length > 0 ? manifest.domainsTouched.map((d) => `- ${d}`).join("\n") : "(none)"}

## Active rules

${activeRules || "(none)"}

_Auto-generated by \`forge manifest\`. Run \`forge manifest --force\` to regenerate._
`;

  return [{ path: ".cursor/rules/contextforge-active.mdc", content }];
}
