import type { AgentManifestResult } from "../agentManifest.js";
import type { RenderedFile } from "./claude.js";

export function renderOpenCode(manifest: AgentManifestResult): RenderedFile[] {
  const skillBullets = manifest.skills
    .map((s) => `- **${s.name}** (${s.matchType}): ${s.reason}`)
    .join("\n");

  const content = `# OpenCode — agent manifest

> Auto-generated by \`forge manifest\`. Consume via MCP tool \`selectAgentContext\` or \`getAgentManifest\`.

## Task

${manifest.task}

## Domains touched

${manifest.domainsTouched.length > 0 ? manifest.domainsTouched.map((d) => `- \`${d}\``).join("\n") : "(none)"}

## Suggested skills

${skillBullets || "(none)"}

## How to call at session start

\`\`\`json
{
  "tool": "selectAgentContext",
  "input": { "task": "${manifest.task.replace(/"/g, '\\"')}" }
}
\`\`\`

The MCP server will compute the manifest in-memory and return it as JSON.
`;

  return [{ path: ".contextforge/manifests/opencode-readme.md", content }];
}
