#!/usr/bin/env node
import path from "node:path";

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

import { createHandlers } from "./handlers.js";

// ─── project root resolution ──────────────────────────────────────────────────

function resolveProjectRoot(): string {
  if (process.env["PROJECT_ROOT"])
    return path.resolve(process.env["PROJECT_ROOT"]);
  let dir = process.cwd();
  for (let i = 0; i < 8; i++) {
    try {
      // sync existence check at startup
      const { statSync } = require("node:fs");
      statSync(path.join(dir, ".contextforge", "graph.json"));
      return dir;
    } catch {
      const parent = path.dirname(dir);
      if (parent === dir) break;
      dir = parent;
    }
  }
  return process.cwd();
}

const PROJECT_ROOT = resolveProjectRoot();
const handlers = createHandlers(PROJECT_ROOT);

// ─── MCP server ───────────────────────────────────────────────────────────────

const server = new McpServer(
  { name: "contextforge", version: "0.1.0" },
  { capabilities: { tools: {} } }
);

server.tool(
  "forge_context",
  "Ranks and selects the most relevant source files for a given task using the pre-built ContextForge dependency graph and Personalized PageRank. Returns a prioritized file list with mode (full/excerpt/summary) that fits a token budget. Use this instead of loading the entire codebase. NOTE: if you are working on an existing OpenSpec change (you see openspec/changes/<id>/), prefer `forge_change_subgraph` first — it returns the frozen, change-scoped subgraph and is much cheaper than recomputing context.",
  {
    task: z
      .string()
      .describe("Natural language description of the task or question"),
    seeds: z
      .array(z.string())
      .optional()
      .describe(
        "File paths to use as starting points for graph traversal (e.g. files you already know are relevant)"
      ),
    budget: z
      .number()
      .int()
      .min(1000)
      .max(50000)
      .optional()
      .default(12000)
      .describe(
        "Max estimated tokens to include in the context pack (default 12000)"
      ),
    include_content: z
      .boolean()
      .optional()
      .default(false)
      .describe(
        "Whether to include actual file content in the response (increases token usage)"
      )
  },
  handlers.forgeContext
);

server.tool(
  "forge_neighbors",
  "Returns the direct neighbors of a file in the dependency graph: what it imports, what imports it, what tests it, and what symbols it defines. Use this to navigate the codebase without reading files. NOTE: when implementing/reviewing an OpenSpec change, call `forge_change_subgraph` FIRST — it gives you the entire frozen scope of the change in one call. Only use `forge_neighbors` after that if you need to walk one specific edge further.",
  {
    file_path: z
      .string()
      .describe(
        "Relative path to the file (e.g. packages/core/src/scanner.ts)"
      ),
    depth: z
      .number()
      .int()
      .min(1)
      .max(3)
      .optional()
      .default(1)
      .describe(
        "Graph traversal depth (1 = direct neighbors only, 2 = neighbors of neighbors)"
      )
  },
  handlers.forgeNeighbors
);

server.tool(
  "forge_domain_map",
  "Returns a high-level map of the project's domains (packages/modules) and their dependencies. Use this to understand project structure without reading package.json files.",
  {},
  handlers.forgeDomainMap
);

server.tool(
  "forge_check",
  "Validates the current git diff against the implement-plan guardrails. Returns pass/fail with specific violations (forbidden paths, files outside allowed list, LOC delta exceeded). Run this before committing to verify compliance.",
  {},
  handlers.forgeCheck
);

server.tool(
  "forge_status",
  "Returns the current state of all ContextForge artifacts: scan freshness, graph stats, context pack summary, implement-plan status, AND a list of OpenSpec changes that have a frozen subgraph (openspec/changes/<id>/graph.subset.json). Use this at the start of a session — if it lists active changes, your next call should usually be `forge_change_subgraph` for the relevant one.",
  {},
  handlers.forgeStatus
);

server.tool(
  "get_agent_manifest",
  "Returns the precomputed agent manifest from .contextforge/agent-manifest.json (generated by 'forge manifest'). Use at session start to see which skills and rules are relevant for the current task.",
  {},
  handlers.getAgentManifest
);

server.tool(
  "forge_archive_change",
  "PRIMARY way to finish a change. Wraps `openspec archive <id>` and then auto-rebuilds the parent graph (.contextforge/graph.json) and refreshes the graph.subset.json of every remaining active change so they reflect the post-archive code. Use this INSTEAD of running `openspec archive` directly via Bash — running archive bare leaves the parent graph stale and silently breaks downstream tools (forge_neighbors, forge_context, other changes' subgraphs). Set skip_openspec_archive=true if you already ran archive yourself and only want the rebuild + refresh part.",
  {
    change_id: z
      .string()
      .min(1)
      .describe(
        "OpenSpec change identifier to archive (the directory name under openspec/changes/)"
      ),
    skip_openspec_archive: z
      .boolean()
      .optional()
      .describe(
        "When true, skip the `openspec archive` call and only run the rebuild + refresh. Use if you already archived manually."
      )
  },
  handlers.forgeArchiveChange
);

server.tool(
  "forge_change_context",
  "Returns the change context map (`openspec/changes/<id>/context.md`) — the curated guide that lists reading order, MCP tool sequence, focus files, and references to global artifacts. Use this AFTER forge_change_subgraph to understand HOW to navigate what the subgraph contains.",
  {
    change_id: z
      .string()
      .min(1)
      .describe(
        "OpenSpec change identifier (the directory name under openspec/changes/)"
      )
  },
  handlers.forgeChangeContext
);

server.tool(
  "forge_change_subgraph",
  'PRIMARY tool when working on an OpenSpec change. Returns the frozen subgraph stored at openspec/changes/<id>/graph.subset.json — exactly the files, symbols, packages and dependencies that were in scope when the spec was authored. Always call this BEFORE forge_context / forge_neighbors when implementing or reviewing a change: it is one cheap call that already answers "what does this change touch and what does it depend on?". The companion artefacts in the same directory (proposal.md, design.md, tasks.md, specs/<domain>/spec.md, context.md, graph.subset.html) are the canonical reading order — see context.md for the map.',
  {
    change_id: z
      .string()
      .min(1)
      .describe(
        'OpenSpec change identifier (the directory name under openspec/changes/, e.g. "fix-token-race")'
      )
  },
  handlers.forgeChangeSubgraph
);

server.tool(
  "select_agent_context",
  "Computes the agent manifest in-memory for the given task — no files written. Returns skills and rules relevant to the task based on the project graph. Use at the start of a conversation or when the task changes.",
  {
    task: z
      .string()
      .min(1)
      .describe("Natural language description of the task"),
    agents: z
      .array(z.enum(["claude", "cursor", "opencode"]))
      .optional()
      .default(["claude", "cursor", "opencode"])
      .describe("Which agent renderers to consider (default: all)")
  },
  handlers.selectAgentContext
);

// ─── transport ────────────────────────────────────────────────────────────────

const transport = new StdioServerTransport();
await server.connect(transport);
